### ISSUE TITLE
Evironment - Quicksand

### ISSUE THREAD

**Issue by StudioTeamTV** [RoadrunnerWMC/Reggie-Updated#25]
Hi i try make my own levels and use quicksand but the quicksand is behaves like a background what should I do to stop it I tried about 50 options and always the same or very similar result

I will be glad for the answers

**Comment by kirbluemodding** [comment]
Hello, what you need to do is find an invisible object in the tileset to solve this issue. In NSMBW, the quicksand sprite only exists as the graphics/model for it. Select an object in the pallette, and hold right on the arrow keys until you have seemingly nothing selected, or just a blue rectangle. Place this down, and you have working collision for your quicksand. (P.S. if you want to find where you placed it, you can do Control or Command + 8 to find the tiles, as they should be marked with an orange arrow facing upwards to a small rectangle)

**Comment by RoadrunnerWMC** [comment]
Thanks for the help, @kirbluemodding, but unfortunately that'll just make the level crash. I can definitely see where that misconception came from, though, since objects with invalid IDs used to look the same as invisible objects in older versions of Reggie. (They don't anymore, since that was too confusing and easy to miss.)

Anyway, to learn how to use sprites that aren't working the way you expect, I recommend looking at a retail level to see how Nintendo did it. 2-2 features quicksand, and here's how one of its quicksand pits looks if you select everything in it (make sure all of the "Freeze (Thing)" settings in the Edit menu are disabled):

![image](https://github.com/NSMBW-Community/Reggie-Updated/assets/8108849/dfd32682-b96c-4f68-81c9-d88b1809c65b)

There are three things there: sprite 53, a location, and an invisible object. Here I've dragged them apart so you can see them more clearly, and hovered my cursor over the object to see what it is:

![image](https://github.com/NSMBW-Community/Reggie-Updated/assets/8108849/41fc3d44-42ba-4b70-9660-15a57601c272)

It's object 24 from tileset 2 (Pa1_sabaku), which is just before the plastic yellow block:

![image](https://github.com/NSMBW-Community/Reggie-Updated/assets/8108849/db8905a4-e10b-4802-9990-c282b86f783c)

It has no graphics, but it is actually what provides the quicksand collision. (I don't know why Nintendo designed it this way.)

Each of the desert-related tilesets has an invisible quicksand-collision object:

- Desert tileset (Pa1_sabaku): object 24
- Desert underground tileset (Pa1_sabaku_chika): object 26
- Desert tower tileset (Pa1_toride_sabaku): object 107

If you need quicksand but aren't using any of those tilesets, you'll have to either load one of them into an available tileset slot (if using NewerSMBW), or edit or create a tileset.

----

I'm going to close this issue since it's just a question, not a problem with the editor itself. Let me know if I didn't explain something clearly enough -- or you can [join the Horizon Discord server](https://discord.gg/XnQJnwa) to get more help there.

Hope that helps!

**Comment by StudioTeamTV** [comment]
THANK YOU SO MUCH I couldn't have done it without you 

btw: i was wondering why when i click on the notes it says "the desert tileset object type 24..." I typed it into the racket as search id 24 but it's buzzy beetle thanks a lot

And how do you create a location?

**Comment by RoadrunnerWMC** [comment]
You're welcome!

Select "Paint New Location" from the top of the Sprites tab, and then you can draw locations by right-clicking-and-dragging:

![image](https://github.com/NSMBW-Community/Reggie-Updated/assets/8108849/9fd86332-933f-4224-ab11-4d4c7c1dbaea)
